### ISSUE TITLE
Can't Make Charcoal! [BUG] 

### ISSUE THREAD

**Issue by AabegR** [ItsSchatten/PortableCraftingInvs#10]
__Please post screenshots on a site like [Imgur](https://imgur.com/upload) and post config files on a site like [Pastebin](https://pastebin.com/) or some another alternative.__

**Please describe the bug**
*What is the bug? What do you think the appropriate behavior would be for this feature? (Paste screenshots here)*

**If there is a stacktrace in console, please post that here.** 
*When an error occurs and you receive the "An internal error has occurred..." message there is some sort of error in console, please copy and past that here.*

**How to reproduce the error?**
*What can I do to reproduce the error you have experienced? Please be detailed.*

**What is your Spigot Version and your plugin list?**
*What version of Spigot are you using? /ver What plugins are you using? /plugins*

**What is the plugins version?**
*Please run '/pci version' in your console or in game and paste it here.*

**Anything else I should know?**
*Is there something else that I should know before attempting to fix this bug?*

Info-
Plugin Version 1.3.2
Spigot 1.16.1
![image](https://user-images.githubusercontent.com/48426374/94051712-ed3f4800-fda5-11ea-800b-f4e31c03da3c.png)

Try Making Charcoal with Oak or Any other kind of Wood via the Furnace

**Comment by ItsSchatten** [comment]
I should mention that I am currently sick with a really bad head cold. I'll work on getting this fixed asap but I'm afraid my health comes before my plugins. Thanks.

**Comment by AabegR** [comment]
Ohhh my...
Don't worry u get better take your break!
Hope you get better soon! 😊
Don't worry about the problems right now it will stress you out listen to some music and take rest.
Enjoy!

**Comment by ItsSchatten** [comment]
I have begun work on tracking this down and getting fixed. Thank you for your patience.

**Comment by AabegR** [comment]
Thank you very much!
You got better real quick 😊

**Comment by ItsSchatten** [comment]
I still don't feel all that well, but I decided I'd do something more productive then sitting in bed all day.

**Comment by AabegR** [comment]
Thats great news, better than before.
Take your time and take breaks

**Comment by ItsSchatten** [comment]
Update was released to spigot :)
