### ISSUE TITLE
Add Chest Support! [Suggestion]

### ISSUE THREAD

**Issue by AabegR** [ItsSchatten/PortableCraftingInvs#11]
I was thinking of having the Support of a Chest! If possible...
I use Minepacks as a Backpack plugin but it has bugs here and there and since this Plugin works completely stable Chests would probably be able to slide in... maybe
Thanks!

**Comment by ItsSchatten** [comment]
I've been asked in the past to make a backpacks plugin of my own but never really got to the "planning" phase. I will consider adding chest support  to PCI, but I feel it might fit better into another plugin such as my own version of a backpack plugin.

That being said, thanks for the suggestion!

**Comment by AabegR** [comment]
Thanks hope to see something new again from you soon!

**Comment by ItsSchatten** [comment]
Closing this as this likely will not be added in this plugin, it will still remain in my mind should I want to develop this into a plugin.

**Comment by AabegRasheed** [comment]
No way! Womp womp hahaha. Good to see you're still developing! I have moved away from running servers but when I used to... I appreciated how well made your plugin was. It always worked and never had a hiccup. Thanks mate :)
