### ISSUE TITLE
Anvil not working properly

### ISSUE THREAD

**Issue by MultiGod** [ItsSchatten/PortableCraftingInvs#12]
So it seems like when players use /anvil it doesn't allow to combine enchants or repair items but its only for some players while others are able to use it normally.

**Comment by ItsSchatten** [comment]
Plugin and spigot ver please?

**Comment by MultiGod** [comment]
version 1.16.1 spigot
PCI version 1.3.2

**Comment by ItsSchatten** [comment]
I've been unable to replicate the issue you describe.

**Comment by MultiGod** [comment]
Ill see if i can get a short clip of the issue

**Comment by MultiGod** [comment]
So I couldnt add videos so i will sending 2 links to unlisted videos
https://youtu.be/WcpMglExuvY
https://youtu.be/E1247I08BNE

**Comment by ItsSchatten** [comment]
Thanks, I'll look into this. My apologies about the inconvenience you've been experiencing. To confirm, does this only happen when attempting to repair the tool with a material (i.e. the diamond sword being repaired with a diamond) or does it also happen when repairing a tool with another variant of that tool (i.e. repairing a damaged diamond sword with another diamond sword)?

**Comment by MultiGod** [comment]
This also happens when trying to repair with another tool as well as trying to enchant an item!

**Comment by ItsSchatten** [comment]
Okay! Thanks for the confirmation, looks as though I might have to redo how the anvil works, it may take some time. I'll keep you updated, again I apologise for the inconvenience the bug causes.

**Comment by MultiGod** [comment]
No worries thank you so much!

**Comment by ItsSchatten** [comment]
I've still been unable to replicate the issue you are having on my test server, I've reset the world let the server run for a few hours, brought on alt accounts, and haven't had the issue you're having. I've slightly updated the code to be a bit more in-line with some other "anvil" plugins to see if that helps anything, however because it isn't a sufficient enough change to release an update for (and because I don't even know if it works) I'm going to finally write the feature request in #7 to the plugin so we have something to at least "release". If you your players are still experiencing these issues in the future, I'll throw in a few more debug messages into the plugin and publish it to this issue. We'll talk more about that later if we need to use it.

You can expect an update to the plugin in about a day. (i'll leave this open until we can at least somewhat confirm that the issue has been "fixed")

**Comment by MultiGod** [comment]
sounds good, im looking forward to it!

**Comment by ItsSchatten** [comment]
I've released an update for the plugin that might resolve this issue. I will opt to keep it open until it can be confirmed.

**Comment by MultiGod** [comment]
Gives me this error now https://pastebin.com/m1vDcU1H

**Comment by ItsSchatten** [comment]
Whoops! I've released an update that will fix this.

**Comment by MultiGod** [comment]
Now when I try to add an enchant or repair an item in /anvil I keep getting a ton of errors like these https://pastebin.com/TRhe0Z9Q

**Comment by ItsSchatten** [comment]
Hi, sorry for the late response, life got in the way of doing my side hobbies. Assuming you're okay with this, I've attached a jar to this message that will hopefully fix the issue you're having (the errors in console) run it and see if the errors are removed, the version will be labeled to 1.3.6-dev so you will receive update notifications. To help test the plugin further could you please provide your plugin list? I have a feeling that somehow someway a plugin is messing with the way my c
anvil is working.

[dev-jar.zip](https://github.com/ItsSchatten/PortableCraftingInvs/files/5392950/dev-jar.zip)

**Comment by MultiGod** [comment]
No worries! I can definitely do that but I am trying to extract the zip but it says it empty and wont allow me to?

**Comment by ItsSchatten** [comment]
Alrighty thanks! Were you able to get the jar from the zip file?

**Comment by MultiGod** [comment]
Yeah i was able too but it didn't seem to be able to fix it unfortunately.

**Comment by MultiGod** [comment]
Hey, hate to be a bother but is there any updates on this?

**Comment by ItsSchatten** [comment]
Hey. I'm sending another jar that might fix the errors in your console, it seems to work for me on my machine at least.

If this does indeed clear your console error problem, could you also confirm that the issues of the Anvils no longer working for some player has also been fixed? I've tried everything that I can think of to stop this from happening besides redoing the entire anvil system; which I really don't want to do, but if I must I will do so.
[unzip-me.zip](https://github.com/ItsSchatten/PortableCraftingInvs/files/5472078/unzip-me.zip)

**Comment by MultiGod** [comment]
so i no longer see errors in console for this but the actual anvil still is not working but I do want to go back to what you said and check through everything again to see if maybe another plugin is causing this issue with the anvils

**Comment by ItsSchatten** [comment]
Any updates about which plugin might be causing issues?

**Comment by ItsSchatten** [comment]
For now I'm going to close this issue until I get an update. If you are still experiencing an issue with the anvil you can reopen this issue.

**Comment by MultiGod** [comment]
Hey firstly, I deeply apologize for not getting to this earlier I was busy with fixing some personal things, anyways I finally found the issue it seems to be protocollib though there doesnt seem to be any errors its just the only plugin that is stopping me from actually using the anvil gui

**Comment by ItsSchatten** [comment]
Don't worry about it! Thanks for getting back to me; I'll have to take a look into the issue a bit more.

**Comment by MultiGod** [comment]
Wondering if there is any other information you need for me :)

**Comment by ItsSchatten** [comment]
Actually yes, would you mind giving the version of ProtocolLib you're using?

**Comment by MultiGod** [comment]
I am using their latest dev build, I can attach a copy if needed

**Comment by ItsSchatten** [comment]
I've still been unsuccessful in replicating your issue.
https://gyazo.com/dad55e80839a9a3d9f060f5dc62a0023
https://gyazo.com/f6bd5b427aa00bda72c66d958a61dd2c

**Comment by MultiGod** [comment]
oddly enough this issue seems to have fixed itself now as well? It is very strange but now it seems all good. I appreciate your work on this and I am sorry if this turned out to be a waste of time ;-; You've been a huge help though! Will definitely continue using this plugin :D

**Comment by ItsSchatten** [comment]
Hmm. That is rather strange I wonder if ProtocolLib was messing with some packet information, guess we'll never really know.

Thanks for the continued support for the plugin!
