### ISSUE TITLE
[BUG] Anvil duplication (severely broken rn)

### ISSUE THREAD

**Issue by Isaiah-labs** [ItsSchatten/PortableCraftingInvs#15]
__Please post multiple screenshots on a site like [Imgur](https://imgur.com/upload) and post config files on a site like [Pastebin](https://pastebin.com/) or some other alternative.__
I have a discord link that a player sent me, it's just him placing an item in an anvil and then exiting and two items move into his inventory (he duped a bow), I'm not sure how to use imgur with videos :/
https://cdn.discordapp.com/attachments/764487669232435200/784941297910939658/video0.mov

**Please describe the bug**
*What is the bug? What do you think the appropriate behavior would be for this feature? (Paste screenshots here)*
Anvils now duplicate all items when hitting escape

**How to reproduce the error?**
*What can I do to reproduce the error you have experienced? Please be detailed.*
Place any item in an anvil and hit escape, it'll duplicate whatever was in the anvil

**What is your Spigot Version and your plugin list?**
*What version of Spigot are you using? /ver What plugins are you using? /plugins*
Paper "git-Paper-261"
I've disabled PCI specifically and the bug is removed so I'm not gonna paste all my plugins since there's a lot (lmk if you do need it regardless lol)

**What is the plugins version?**
*Please run '/pci version' in your console or in game and paste it here.*
Latest version - 1.3.9

**Anything else I should know?**
*Is there something else that I should know before attempting to fix this bug?*
It's definitely gotta be because of the recent anvil change where it moves items back into your inventory--

**Comment by Isaiah-labs** [comment]
Okay so messing around with things a bit more: 
The dupe bug was occurring with normal anvils, not /anvil (in 1.3.9)
I moved back to 1.3.8 and the bug isn't present with real anvils but it does still erase items that are being used in /anvil

Hopefully this helps!

**Comment by ItsSchatten** [comment]
Thanks for the report! This is due to the way I had to return the player's items when closing a virtual anvil; there should be a fix in about an hour or so. Apologies for the inconvenience.

**Comment by Isaiah-labs** [comment]
Appreciate the quick fix! Love your work ;)

**Comment by ItsSchatten** [comment]
No problem! If you or your players run across any other issues please let me know!
