### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by hexagon02** [ItsSchatten/PortableCraftingInvs#16]
Hi! I really appreciate your plugin Portable Crafting Inventories! I'm using it a lot and it is really useful.
My only problem with that is about the storage method: when players begin to be many (i'm using the plugin on a server with 150 players connected simultaneously, so the accounts stored are thousands), the inventories opening lags.
Would be possible to add a MySQL database support instead of the data folder? I am ready, in case, to pay you for a private commission or a fork of the plugin that supports MySQL (if possible obv!)
Let me know, and again great job!

**Comment by ItsSchatten** [comment]
Hey!

Thanks for the suggestion! Purchasing a private fork for SQL storage will not be necessary, I feel this feature would improve the experience for all server owners using the plugin.

**Comment by hexagon02** [comment]
So, are you planning to add this feature?

**Comment by ItsSchatten** [comment]
I am indeed.

**Comment by hexagon02** [comment]
Awesome! Could you give me an ETA? :D

**Comment by ItsSchatten** [comment]
Because I'll likely have to rewrite how the FurnaceManager class works it'll likely take at least a day with the maximum being 3 or 4; I'll be sure to post here if I run into any issues that might impact the time it'll take.

**Comment by hexagon02** [comment]
I can't wait for this update bro! Rly awesome ;))
