### ISSUE TITLE
[Suggestion] Brewing Stand Support

### ISSUE THREAD

**Issue by dotxzxc** [ItsSchatten/PortableCraftingInvs#17]
**What is your suggestion?**
Brewing Stand support

**Comment by ItsSchatten** [comment]
I feel I should leave a comment here for a progress update:

I've began work on this feature, actually at the time of writing this I've been working on it for five hours now. I've currently stumbled upon an issue that has broken Furnaces and doesn't quite get brewing stands working. I do expect this feature to be complete in the coming days (if not tomorrow), though for today I going to take a break.

**Comment by ItsSchatten** [comment]
If this doesn't work as expected please open a new issue.
