### ISSUE TITLE
[BUG] Reloading plugin and /furnace doesn't work

### ISSUE THREAD

**Issue by Cacteu** [ItsSchatten/PortableCraftingInvs#19]
__Please post multiple screenshots on a site like [Imgur](https://imgur.com/upload) and post config files on a site like [Pastebin](https://pastebin.com/) or some other alternative.__

**Please describe the bug**
*What is the bug? What do you think the appropriate behavior would be for this feature? (Paste screenshots here)*

When I try to do /pci rl and /furnace, it gives me the same error.
https://i.imgur.com/dnjM7QB.png

**If there is a stack trace in console, please post that here.** 
*When an error occurs and you receive the "An internal error has occurred..." message there is some sort of error in console, please copy and past that here.*

https://pastebin.com/B1wpLUwb
https://pastebin.com/rFPVFnx0

**How to reproduce the error?**
*What can I do to reproduce the error you have experienced? Please be detailed.*
Just do /pci reload and /furnace

**What is your Spigot Version and your plugin list?**
*What version of Spigot are you using? /ver What plugins are you using? /plugins*

Tuinity version git-Tuinity-"d3ee222" (MC: 1.16.5) Implementing API version 1.16.5-R0.1-SNAPSHOT

**What is the plugins version?**
*Please run '/pci version' in your console or in game and paste it here.*

1.5.1

**Anything else I should know?**
*Is there something else that I should know before attempting to fix this bug?*
I tried doing /furnace in another similar server with the same version and it works as intended.
But when I checked the furnaces.yml in the server where it doesn't work, it only generates config for smokers. I deleted the config and restarted the server and same thing happens.

**Comment by ItsSchatten** [comment]
If you are still experiencing a similar issue to this one, please reopen this issue.
