### ISSUE TITLE
[BUG] Brew stands dont brew anything tier 2+

### ISSUE THREAD

**Issue by lewismercer** [ItsSchatten/PortableCraftingInvs#22]
As the title suggests, it does the first brew fine and then anything after this doesnt work.

**Comment by ItsSchatten** [comment]
This requires more information, I'm capable of brewing all tier 2 potions just fine on the latest version of Spigot.

**What version of Spigot are you using?**

**Comment by lewismercer** [comment]
I am using paper #46, as far as I am aware any plugin that's coded currently with spigot should be fine on paper?
________________________________

**Comment by ItsSchatten** [comment]
Using Paper #49 I cannot replicate your issue.

**Comment by ItsSchatten** [comment]
Closing this as I'm unable to replicate the issue described.
