### ISSUE TITLE
[BUG] Enchantments on hover are completely different to what you get

### ISSUE THREAD

**Issue by lewismercer** [ItsSchatten/PortableCraftingInvs#23]
Again, title says it all however i understand that why you are faking an ectable that there might be nothing you can do about it? Not sure if you can fix it with NMS?

**Comment by ItsSchatten** [comment]
This requires more information.

If you're opening the enchantment table with a changed max level it will unfortunately be different due to the way I'm forced to open an enchantment table with an alternate level.

**Comment by lewismercer** [comment]
Ah okay, had a bad feeling that's what you would say - sorry about that!
________________________________

**Comment by ItsSchatten** [comment]
See the newest update for this
