### ISSUE TITLE
[BUG] Dupe glitch

### ISSUE THREAD

**Issue by lewismercer** [ItsSchatten/PortableCraftingInvs#25]
**Please describe the bug**
If you exit /anvil with an item in the 2nd slot it dupes it - found by an honest player on my server and had to disable /anvil

**Comment by lewismercer** [comment]
This is also latest version of both paper and pci

**Comment by ItsSchatten** [comment]
Fixed in [0003136](https://github.com/ItsSchatten/PortableCraftingInvs/commit/000313692a76cffd63bd46e4a96c60a597b2b615)
