### ISSUE TITLE
[Suggestion] Add anvil support for external plugins.

### ISSUE THREAD

**Issue by Craftizz** [ItsSchatten/PortableCraftingInvs#27]
**What is your suggestion?**
*What is the suggestion you are proposing?*
When using the portable anvil, other plugins that have anvil features such as reducing XP cost, custom enchantment, etc. is not working. Please add support to it

**How should this suggestion work?**
*How should I attempt to make this suggestion work?*
The normal way anvils work.

**Anything else you need to add?**
Thanks for this awesome plugin!

**Comment by ItsSchatten** [comment]
Would you mind providing a plugin as an example for this?

**Comment by Craftizz** [comment]
Aurelium Skills: https://github.com/Archy-X/AureliumSkills
EcoEnchants: https://github.com/Auxilor/EcoEnchants

**Comment by ItsSchatten** [comment]
I've resolved this issue in testing however I'm going to wait a bit longer to release it so I can fully debug it (and will hopefully give some time for Paper to update to fix the inventory not animating issue).
