### ISSUE TITLE
[BUG] Enchant Table Level not working

### ISSUE THREAD

**Issue by Craftizz** [ItsSchatten/PortableCraftingInvs#28]
**Please describe the bug**
*What is the bug? What do you think the appropriate behavior would be for this feature? (Paste screenshots here)*
When opening /enchanttable 30, it outputs an error

**If there is a stack trace in console, please post that here.** 
*When an error occurs and you receive the "An internal error has occurred..." message there is some sort of error in console, please copy and past that here.*
https://pastebin.com/fRYKZLcz

**How to reproduce the error?**
*What can I do to reproduce the error you have experienced? Please be detailed.*
Type /enchanttable 30

**What is your Spigot Version and your plugin list?**
*What version of Spigot are you using? /ver What plugins are you using? /plugins*
Tuinity 1.17.1

**What is the plugins version?**
*Please run '/pci version' in your console or in game and paste it here.*
1.6.6

**Comment by ItsSchatten** [comment]
Confirmed; should be a release soon that will resolve this issue. Thank you for the report.
