### ISSUE TITLE
[BUG] Furnace has no animation

### ISSUE THREAD

**Issue by Craftizz** [ItsSchatten/PortableCraftingInvs#29]
__Please post multiple screenshots on a site like [Imgur](https://imgur.com/upload) and post config files on a site like [Pastebin](https://pastebin.com/) or some other alternative.__
https://imgur.com/a/umifG3s

**Please describe the bug**
*What is the bug? What do you think the appropriate behavior would be for this feature? (Paste screenshots here)*
The /furnace has no furnance animation

**How to reproduce the error?**
*What can I do to reproduce the error you have experienced? Please be detailed.*
Smelt any blocks on /furnace

**What is your Spigot Version and your plugin list?**
*What version of Spigot are you using? /ver What plugins are you using? /plugins*
Tuinity 1.17.1

**What is the plugins version?**
*Please run '/pci version' in your console or in game and paste it here.*
1.6.6

**Comment by ItsSchatten** [comment]
Known issue with Paper and forks.

**Comment by ItsSchatten** [comment]
Issue opened https://github.com/PaperMC/Paper/issues/6184

**Comment by ItsSchatten** [comment]
As an update to this: this has been fixed in https://github.com/PaperMC/Paper/commit/501834e57a7a343003c6f81757ec616be95a55dd
