### ISSUE TITLE
Suggestion: Disable Chat Message

### ISSUE THREAD

**Issue by Ing1011** [ItsSchatten/PortableCraftingInvs#3]
**Suggestion**
Add an option to toggle chat messages when using the commands.
Doing "" in messages.yml gives an empty line every time.

**How should this suggestion work?**
Add "use_X_messages" in the settings.yml to toggle messages in the chat.

**Anything else you need to add?**
This plugin is simple and awesome. Thanks for updating it to 1.13.2!

**Comment by ItsSchatten** [comment]
Thank you for your suggestion! I will begin working on this suggestion as soon as I can.

**Comment by ItsSchatten** [comment]
Thank you again for your suggestion. Instead of adding a ton of booleans in the settings.yml file I went ahead and just added the ability to set the message to "" and they shouldn't appear.
