### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Just-Henk** [ItsSchatten/PortableCraftingInvs#32]
how do I give the player permission to use the command without op them?

**Comment by ItsSchatten** [comment]
You can use a permissions plugin to do give specific permissions to a user or group or you can change the 'use-permissions' setting in the settings.yml to false and all crafting commands will be available to all players.

**Comment by Just-Henk** [comment]
ok thx

**Comment by ItsSchatten** [comment]
If you have any more questions or issues, please reopen this issue.
