### ISSUE TITLE
[BUG] | Furnace not wokring 

### ISSUE THREAD

**Issue by Mountain011** [ItsSchatten/PortableCraftingInvs#33]
### What is the version of the plugin you''re using?

1.18.1

### What is your Spigot version?

latest paper

### Please describe the bug.

Furncace doesnt open when using /furnace

### Please list your plugins.

d

### Anything else to add?

d

**Comment by ItsSchatten** [comment]
Please provide any error logs that may be thrown in console.  I was unable to confirm this on my end.

**Comment by Mountain011** [comment]
there is no errors that come up i go into the serevr and it just asays i issues command /furnace and but it doesnt appear on screen

**Comment by ItsSchatten** [comment]
Please make sure you have the latest version of the plugin (version 1.7.1), I tested with Paper 215 and haven't experiences this issue. It might also be worth testing the other furnace commands such as /smoker and /blastfurnace, if those work you likely have a plugin conflict.

Additionally, make sure you have furnaces enabled in the 'settings.yml' and a plugin doesn't override the command /furnace command.

**Comment by ItsSchatten** [comment]
Marking as resolved and closing; if you are still experiencing this issue please provide more information (such as if other furnace commands work appropriately) and if possible a list of your plugins.
