### ISSUE TITLE
[FEATURE] | Recycler

### ISSUE THREAD

**Issue by iblacksheep** [ItsSchatten/PortableCraftingInvs#35]
### Please describe the feature.

Add the feature of being able to "uncraft" items. Because the word salvage is so closely associated with McMMO, I suggest the term Recycler. This would open a gui to turn items into the materials used to craft them. A now-abandoned project already has the groundwork for this completed and is open source. It may be viewed at https://github.com/Siguza/VirtualPack.

Using VirtualPack in my earlier days as an admin is what brought me to PCI, and seeing the expanded functionality would make me giddy. It would also be highly useful.

**Comment by ItsSchatten** [comment]
Thanks for the suggestion! I'll see what I can do.

**Comment by ItsSchatten** [comment]
Going to close this as it doesn't fit the "theming" of this plugin. Because I still like this idea I may end up creating a standalone plugin for this.
