### ISSUE TITLE
An Internal error occurred while attempting to perform this command /enchant /anvil

### ISSUE THREAD

**Issue by MeepDaSheep** [ItsSchatten/PortableCraftingInvs#38]
im using spidgot and portablecraftingInvs for 1.19 and im getting the error "An Internal error occurred while attempting to perform this command" whenever i try to run /enchant and /anvil

**Comment by ItsSchatten** [comment]
Do you happen to have a console log of this error happening? Should also be noted that I build 1.19 builds using the latest 1.19 version (in this case 1.19.3), if you're using an outdated version let me know.

**Comment by ItsSchatten** [comment]
Closing for now; cannot seem to replicate and console log has not been provided yet.

If you do encounter the issue again please reopen this.
