### ISSUE TITLE
access

### ISSUE THREAD

**Issue by Huiqqqqqq** [ItsSchatten/PortableCraftingInvs#39]
How to make the furnace, chest, anvil accessible to everyone?

**Comment by ItsSchatten** [comment]
You may change the 'use-permissions` option in the settings.yml file to allow anyone to open any inventory. If you only want players to have access to just furnaces, ender chests, and anvils you'll have to disable the other features in the settings.yml.

If you aren't opposed to using a permissions plugins such as [LuckPerms](https://luckperms.net/download), you can then give your default group the following permissions:
- **pci.anvil**
- **pci.furnace** (if you want the other types of furnaces **pci.blast-furnace** and **pci.smoker**)
- **pci.enderchest**

Any other permissions you may wish to use are listed on the [resource page](https://www.spigotmc.org/resources/portable-crafting-inventories-completely-customizable.61045/field?field=documentation).

**Comment by Huiqqqqqq** [comment]
that is, if the player writes the stove (nickname), then the player's stove will open

**Comment by ItsSchatten** [comment]
Yes, assuming the player has appropriate permission or permissions are disabled via the config file. They should be able to open a furnace (or any other inventory)

**Comment by ItsSchatten** [comment]
Closing this for now; if you require more assistance please open a new issue.

It should be noted that if you have both essentials and pci installed you may encounter issues on Paper, changing the `allow-essentials` option in the config should allow pci to override their commands.
