### ISSUE TITLE
/brewing cant create Mundane Potions

### ISSUE THREAD

**Issue by NeverGrowUp** [ItsSchatten/PortableCraftingInvs#43]
### What is the version of the plugin you''re using?

1.7.10

### What is your Spigot version?

 Paper version git-Paper-171 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 33bec7f)

### Please describe the bug.

Using a normal brewing stand, place water bottle at the bottom and Magma_Cream at the top (or any other ingredient for mundane potion, (Glistering Melon, Spider eyes, Sugar, Blaze Powder, Ghast Tears, or Redstone Dust)) and it creates a Mundane Potion.
But when using /brewing command (or [brew] sign), when you put the ingredients in, nothing occurs.

Also tested with PCI 1.7.8 and 1.7.9 to no avail.

### Please list your plugins.

PortableCraftingInv only

**Comment by ItsSchatten** [comment]
Thanks for the report. I'll get it fixed asap.
