### ISSUE TITLE
Duplicate commands

### ISSUE THREAD

**Issue by Xlikes** [ItsSchatten/PortableCraftingInvs#48]
I use a plugin that also uses /ec. Now I have the problem that I can only deactivate or activate /ec with the plugin... So either the normal ec opens and after closing the customized one via separate plugin or the command is blocked. both not really acceptable.

**Comment by ItsSchatten** [comment]
I apologize for getting back to this so late. 

For this, do you still wish to use PCI's implementation of ender chests?

**Comment by ItsSchatten** [comment]
Fixed in 2.0.0
