### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by askb20** [ItsSchatten/PortableCraftingInvs#50]
Hi, I'm relatively new to using gradle, and I've been trying my best to figure this out this whole afternoon. I have successfully built nms-remap-plugin, however when I then try to build PCI, it gives me this error regarding ShadowLibs. I've been unable to build shadowlibs myself locally so far. This could just be a me issue, but I would appreciate some help.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':paper:shadowJar'.
> Could not resolve all dependencies for configuration ':paper:runtimeClasspath'.
   > Could not find com.itsschatten.libs:ShadowLibs:1.0.10.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/itsschatten/libs/ShadowLibs/1.0.10/ShadowLibs-1.0.10.pom
       - file:/Users/askb/.m2/repository/com/itsschatten/libs/ShadowLibs/1.0.10/ShadowLibs-1.0.10.pom
       - https://repo.codemc.org/repository/maven-public/com/itsschatten/libs/ShadowLibs/1.0.10/ShadowLibs-1.0.10.pom
       - https://repo.papermc.io/repository/maven-public/com/itsschatten/libs/ShadowLibs/1.0.10/ShadowLibs-1.0.10.pom
     Required by:
         project :paper
```

**Comment by ItsSchatten** [comment]
To quickly remedy this you should be able to clone https://github.com/ItsSchatten/ShadowLibs and run `clean build` to build the library. Otherwise, if you can wait until sometime tomorrow (later today technically, as I'm writing this at 2am...) I should be able to have an alternative solution.

**Comment by ItsSchatten** [comment]
Updates!

1. https://github.com/ItsSchatten/ShadowLibs has been updated to reflect changes that I forgot to push, whoops.
2. ShadowLibs can now be accessed via GitHub Packages, I'll leave that configuration below.
	* PCI has been updated to reflect the usage of GitHub Packages as well.
	* You will still be required to follow https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#authenticating-to-github-packages in order to access the package.

If you need any more help with this, let me know.

_Because PCI uses Kotlin DSL this example will use that_
[See GitHub's documentation for additional information.](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package)
```gradle
dependencies {
	implementation("com.itsschatten.libs:shadowlibs:1.0.10");
}

maven {
        url = uri("https://maven.pkg.github.com/ItsSchatten/ShadowLibs")
        credentials {
            // These are placed in the .gradle/gradle.properties file.
            // Keep the names in mind as they must match to be used.
            username = project.findProperty("gpr.username") as String
            password = project.findProperty("gpr.token") as String
        }
    }
```

I'm going to close this issue, please reopen it if you encounter any issues.
