### ISSUE TITLE
[BUG] | not found certain commands

### ISSUE THREAD

**Issue by Zarkness** [ItsSchatten/PortableCraftingInvs#51]
### PCI Information

2.0.0-SNAPSHOT

### Describe the Bug

only the /ec and /wb command works, the others give me an error like this one https://paste.helpch.at/uteyudakib.rb

### What plugins are you running?

![image](https://github.com/user-attachments/assets/9e4df2d1-5917-4ae4-bb04-4cfc7c5683e9)
![image](https://github.com/user-attachments/assets/857323be-5922-4927-8a9b-f49e138a315c)

### Anything else?

Version server: This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version
Previous version: git-Purpur-2176 (MC: 1.20.4)

**Comment by ItsSchatten** [comment]
Would you mind sending a log when starting the server? There should be an error message regarding "Fake Containers".

**Comment by Zarkness** [comment]
[2024-09-10-1.log](https://github.com/user-attachments/files/16940946/2024-09-10-1.log)

**Comment by ItsSchatten** [comment]
This appears to be an issue with breaking changes between 1.20.4 and 1.21.

Unfortunately, I don't think I'd be able to make it compatible without regressions to the API with some of the item component API introduced in 1.21, but I will see if I'm able to do something. I will release a quick update so you can continue to use the plugin without the use of the virtual brewing stands.

**Comment by ItsSchatten** [comment]
Quick little update to this; if you can update to 1.20.6 or 1.21.1. These versions should support the changes.
