### ISSUE TITLE
Add option to pay for certain amount of uses in anvil

### ISSUE THREAD

**Issue by broken1arrow** [ItsSchatten/PortableCraftingInvs#7]
Suggestions are always welcome and I appreciate all of them. However, please note that not all suggestions just cannot be implemented.

**What is your suggestion?**
When use anvil command, it has no downsides (normal anvil breaks after use too mush).
**What is the suggestion you are proposing?**
So when player has use anvil X amount of time, he had to pay (items or money) for use it again 
**How should this suggestion work?**
When in gui, you get msg if anvil has no more uses and how to pay/give it item.
**How should I attempt to make this suggestion work?**
Make a command like /anvil charge 10 
(you get 10 uses)
Player get this MSG "{playername} have charge anvil with {amount} of uses.
**Anything else you need to add?**
I don't say how you shall implemented, but give only suggestions (when you add this line in Feature request, I try too answer this too).

**Comment by ItsSchatten** [comment]
Would you prefer these charges to be renewed after a server restart or after a certain amount of time? Say it takes you two real life hours to renew one charge for your anvil?

**Comment by broken1arrow** [comment]
> 
> 
> Would you prefer these charges to be renewed after a server restart or after a certain amount of time? Say it takes you two real life hours to renew one charge for your anvil? Or would you like all players to have a specific set of "free" charges that would then run out after you use the maximum amount of charges set in the config, after you would have to pay to use the anvil.

I think of the last part, when players have  specific set of "free" charges and have to pay to get more. 

The other two i think upset the players too much :)

**Comment by ItsSchatten** [comment]
Alright! Thanks for the feedback I shall begin working on this suggest as soon as I possibly can!

**Comment by broken1arrow** [comment]
How is going with this ?

**Comment by ItsSchatten** [comment]
I've opted to make an addon plugin to implement this feature, I've begun working on it today, it will likely be released either late today or sometime tomorrow (a link will be posted here when it is finally released.)

Apologies for the wait time.

**Comment by broken1arrow** [comment]
> I've opted to make an addon plugin to implement this feature, I've begun working on it today, it will likely be released either late today or sometime tomorrow (a link will be posted here when it is finally released.)
> 
> Apologies for the wait time.

No problems, sounds nice.

**Comment by ItsSchatten** [comment]
As an update to this:

I have the main plugin mostly updated to support this new addon plugin, the addon plugin is completely done. I have some final touches (like making sure the opened inventory message & sound isn't sent to the executer of the command if they don't have enough money or a free charge).

Unfortunately its currently rather late at the time of writing this and I have some things that I must attend tomorrow; I will certainly try to have the plugin completed tomorrow.

**Comment by ItsSchatten** [comment]
https://www.spigotmc.org/resources/pci-economy.93136/

**Comment by ItsSchatten** [comment]
I'm going to close this for now; should you find an issue or need support for your requested feature please open a new issue at https://github.com/ItsSchatten/PCI_Economy/issues
