### ISSUE TITLE
Furnaces/Smoker/Blast not Working for Regular Players

### ISSUE THREAD

**Issue by AabegR** [ItsSchatten/PortableCraftingInvs#9]
Crafting is working and everything else... Remember I had issue with the furnaces earlier ya I got another problem.
Regular players cant open furnace, it was working for 20 mins and it just randomly died but op players can still access it

**Comment by AabegR** [comment]
Also, Anvil is not Working for players without OP (they have the perms and was working before)

**Comment by ItsSchatten** [comment]
I am unable to replicate what you are experiencing. Perhaps resetting the furnace.yml and the playerdata files will help to fix the issue.

If there are no errors in console or the player's aren't receiving any messages in chat, I'm afraid I'm at a loss.

**Comment by AabegR** [comment]
That issue disapearred and now magically I have another issue, my players that has permissions cannot open anvil and it wouldn't come up in tab as well.
Also about the tab options... only craft and furnace show up. OP doesn't have any problems! :)

**Comment by ItsSchatten** [comment]
I'm still unable to replicate this issue. Could you please enable debug in the settings.yml, have your players attempt the anvil commands and then send me the log to see where it's failing? It would be beneficial to have the full log, from the start of the server up until you send it to me so I can look through the entire log for anything that might help me solve this issue. Please provide your log file either on https://pastebin.com or https://paste.md-5.net and paste the link back to this issue; feel free to remove personal information about your server and players (i.e. the IP address of a player.)

The commands are setup in a way that only allow users with permissions to tab them (the same permission to run the command, in this case it would be pci.anvil). If a player has permission pci.anvil, they will be able to tab /anvil and run the command.

**Comment by AabegR** [comment]
Oh um, things are good now somehow... Its all working.. cul

Thanks for your help and I love the plugin btw even tho I got the problems lol but still if 1 thing works that's at least better than having nothing! :) Thnx for creating this plugin I hope you continue to improve and update this!
